version: '3.8'

services:
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq_service 
    restart: always 
    environment:
      RABBITMQ_DEFAULT_USER: test1
      RABBITMQ_DEFAULT_PASS: 123123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - app_network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf



  rabbitmqManager:
    build: .
    container_name: rabbitmq_manager
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8000:8001"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge



